name: Create release assets
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
permissions:
    contents: write
jobs:
  build-files:
    name: Build data files
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:10.0-preview
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Install .NET tool
        run: |
          dotnet new tool-manifest
          dotnet pack ./src/tool/ --output ./pkg /p:PackageVersion=0.0.0
          dotnet tool install --add-source ./pkg Examples.SampleData.Tool
      - name: Create output directory
        run: |
          mkdir -p ./out
      - name: Build data files
        run: |
          dotnet tool run datagen ./data/ --output-file ./out/data.xml --output-format xml
          dotnet tool run datagen ./data/ --output-file ./out/data.json --output-format json
          dotnet tool run datagen ./data/ --output-file ./out/data.csv --output-format csv
          dotnet tool run datagen ./data/ --output-file ./out/data.yml --output-format yaml
      - name: Upload data file artifact
        uses: actions/upload-artifact@v4
        with:
          name: Data files
          path: ./out/data.*
  create-release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    needs: 
      - build-files
    steps:
      - name: Create release
        uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.run_number }}"
          release_name: "Release ${{ github.run_number }}"
          draft: false
          prerelease: false
      - name: Download data file artifact
        uses: actions/download-artifact@v4
        with:
          name: Data files
      - name: Upload XML data release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./data.xml
          asset_name: data.xml
          asset_content_type: application/xml
      - name: Upload JSON data release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./data.json
          asset_name: data.json
          asset_content_type: application/json
      - name: Upload CSV data release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./data.csv
          asset_name: data.csv
          asset_content_type: text/csv
      - name: Upload YAML data release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./data.yml
          asset_name: data.yml
          asset_content_type: application/x-yaml
      
          